goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.array', 'goog.object', 'goog.string.StringBuffer']);
goog.addDependency("../om/dom.js", ['om.dom'], ['cljs.core']);
goog.addDependency("../om/core.js", ['om.core'], ['cljs.core', 'om.dom', 'goog.ui.IdGenerator']);
goog.addDependency("../frontpage_client/facets.js", ['frontpage_client.facets'], ['cljs.core', 'om.core', 'om.dom']);
goog.addDependency("../cljs/core/async/impl/protocols.js", ['cljs.core.async.impl.protocols'], ['cljs.core']);
goog.addDependency("../cljs/core/async/impl/buffers.js", ['cljs.core.async.impl.buffers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/dispatch.js", ['cljs.core.async.impl.dispatch'], ['cljs.core.async.impl.buffers', 'cljs.core']);
goog.addDependency("../frontpage_client/pagination.js", ['frontpage_client.pagination'], ['cljs.core', 'om.core', 'om.dom']);
goog.addDependency("../cljs/core/async/impl/ioc_helpers.js", ['cljs.core.async.impl.ioc_helpers'], ['cljs.core', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/channels.js", ['cljs.core.async.impl.channels'], ['cljs.core.async.impl.buffers', 'cljs.core', 'cljs.core.async.impl.dispatch', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async/impl/timers.js", ['cljs.core.async.impl.timers'], ['cljs.core', 'cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core.async.impl.protocols']);
goog.addDependency("../cljs/core/async.js", ['cljs.core.async'], ['cljs.core.async.impl.ioc_helpers', 'cljs.core.async.impl.buffers', 'cljs.core', 'cljs.core.async.impl.channels', 'cljs.core.async.impl.dispatch', 'cljs.core.async.impl.protocols', 'cljs.core.async.impl.timers']);
goog.addDependency("../frontpage_client/solr.js", ['frontpage_client.solr'], ['cljs.core', 'goog.json', 'goog.net.XhrIo', 'cljs.core.async', 'goog.Uri']);
goog.addDependency("../clojure/walk.js", ['clojure.walk'], ['cljs.core']);
goog.addDependency("../cljs/reader.js", ['cljs.reader'], ['cljs.core', 'goog.string']);
goog.addDependency("../clojure/set.js", ['clojure.set'], ['cljs.core']);
goog.addDependency("../datascript.js", ['datascript'], ['cljs.core', 'clojure.walk', 'cljs.reader', 'clojure.set']);
goog.addDependency("../frontpage_client/statistics.js", ['frontpage_client.statistics'], ['datascript', 'cljs.core', 'om.core']);
goog.addDependency("../frontpage_client/document.js", ['frontpage_client.document'], ['cljs.core', 'om.core', 'frontpage_client.solr', 'om.dom', 'cljs.core.async', 'frontpage_client.statistics']);
goog.addDependency("../clojure/browser/event.js", ['clojure.browser.event'], ['cljs.core', 'goog.events.EventType', 'goog.events.EventTarget', 'goog.events']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['cljs.core', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../secretary/core.js", ['secretary.core'], ['cljs.core', 'clojure.walk', 'clojure.string']);
goog.addDependency("../frontpage_client/util.js", ['frontpage_client.util'], ['cljs.core', 'om.core', 'om.dom']);
goog.addDependency("../frontpage_client/core.js", ['frontpage_client.core'], ['frontpage_client.facets', 'frontpage_client.document', 'datascript', 'frontpage_client.pagination', 'cljs.core', 'secretary.core', 'om.core', 'frontpage_client.solr', 'clojure.string', 'frontpage_client.util', 'om.dom', 'cljs.core.async', 'frontpage_client.statistics']);
goog.addDependency("../clojure/browser/net.js", ['clojure.browser.net'], ['goog.net.xpc.CrossPageChannel', 'clojure.browser.event', 'goog.net.xpc.CfgFields', 'cljs.core', 'goog.net.EventType', 'goog.json', 'goog.net.XhrIo']);
goog.addDependency("../clojure/browser/repl.js", ['clojure.browser.repl'], ['clojure.browser.event', 'clojure.browser.net', 'cljs.core']);
goog.addDependency("../piggieback_browser.js", ['piggieback_browser'], ['cljs.core', 'clojure.browser.repl']);